version: '2'
services:
  db:
    image: mysql:5.7
    container_name: renaceruk_mysql
    restart: always
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 6D2jeu6kHoXwq2BXpB02oN
      MYSQL_DATABASE: db_renaceruk
      MYSQL_USER: user_renaceruk
      MYSQL_PASSWORD: 6D2jeu6kHoXwq2BXpB02oN
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    container_name: renaceruk_wordpress
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./www:/var/www/html"
      - "./config/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: db_renaceruk
      WORDPRESS_DB_USER: user_renaceruk
      WORDPRESS_DB_PASSWORD: 6D2jeu6kHoXwq2BXpB02oN
  server:
    # image: bushrangers/alpine-caddy:latest
    image: caddy:2-alpine
    container_name: renaceruk_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - wordpress
    volumes:
      - "./config/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./config/caddy/data:/data"
      - "./config/caddy/config:/config"
    volumes_from:
      - wordpress